# Generated by Django 2.0.2 on 2018-04-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='No title', max_length=50)),
                ('pub_dae', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parqueadero.Propietario')),
            ],
        ),
    ]
