# Generated by Django 2.0.2 on 2018-04-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0003_auto_20180424_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
