# Generated by Django 2.0.2 on 2018-04-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0004_vehiculo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='title',
            field=models.CharField(default='No title', max_length=50),
        ),
    ]
