# Generated by Django 2.0.2 on 2018-04-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0005_vehiculo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='nombre',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='pub_dae',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='title',
        ),
    ]
