# Generated by Django 2.0.2 on 2018-04-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0006_auto_20180425_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
    ]
